### ISSUE TITLE
What is the licence for this code?

### ISSUE THREAD

**Issue by HubertReX** [CodingQuest2023/Algorithms#2]
Hi 👋 

I really like the solutions provided in this repo. I'd like to adopt it to my game, but there is no license or copyright notice. My game might be paid in the future, but I'm an amateur solo dev and I don't expect ever to get more than 100$ in total ;-) For now, it's open source.

If you want to have a look at the current state, here's a link:
[pygame-ce-web-boilerplate](https://github.com/HubertReX/pygame-ce-web-boilerplate)

**Comment by CodingQuest2023** [comment]
Hi,

Sorry for the late reply. Feel free to use any of the code in your own
projects.

CodingQuest
